### ISSUE TITLE
夜晚颜色怎么不太一样？——大气吸收

### ISSUE THREAD

**Issue by YDX-2147483647** [Devil-SX/WhySkyisBlue#1]
光谱除了受黑体辐射、Rayleigh散射影响，还受太阳和地球的大气影响。大气中的气体可能受激发，直接把特定波长的光吸收掉。

https://en.wikipedia.org/wiki/Diffuse_sky_radiation

> In [Earth's atmosphere](https://en.wikipedia.org/wiki/Earth%27s_atmosphere), the dominant scattering efficiency of [blue light](https://en.wikipedia.org/wiki/Sky_blue) is compared to [red or green](https://en.wikipedia.org/wiki/Visible_spectrum#Spectral_colors) light. Scattering and **absorption** are major causes of the [attenuation](https://en.wikipedia.org/wiki/Attenuation) of sunlight radiation by the atmosphere.
> - During broad [daylight](https://en.wikipedia.org/wiki/Daylight), the sky is blue due to [Rayleigh scattering](https://en.wikipedia.org/wiki/Rayleigh_scattering),
> - while around sunrise or sunset, and especially during [twilight](https://en.wikipedia.org/wiki/Twilight), **[absorption](https://en.wikipedia.org/wiki/Chappuis_absorption) of irradiation by [ozone](https://en.wikipedia.org/wiki/Ozone#Spectroscopic_properties)** helps maintain blue color in the evening sky.
> - At sunrise or sunset, tangentially incident solar rays illuminate clouds with orange to red hues.

---

> 只散射一次，且正午太阳直射，我们以 90° - θ 角度抬起脑袋仰望天空，

另外，我很怀疑“单次”散射。Rayleigh散射不同方向的相对强度分布与波长无关，单次散射的话各个方向都是这个颜色。然而直视太阳更接近白色呀。

[![Skyshot](https://github.com/user-attachments/assets/e63dda0a-1906-4c24-8c85-60992cab29bb)](https://commons.wikimedia.org/wiki/File:Skyshot.jpg)

[![Trees-sky](https://github.com/user-attachments/assets/5ba441fe-c852-4bf3-afba-7407f018b0b1)](https://commons.wikimedia.org/wiki/File:Trees-sky.jpg)

---

我之前听说的版本是黑体辐射谱里紫光太少，所以最后人看到的是白光。今天看到你讨论颜色混合，觉得更有道理。

**Comment by Devil-SX** [comment]
# 直视太阳为什么是白色？

我在blog中假设的是这么一种情形：
![未命名绘图 drawio](https://github.com/user-attachments/assets/1de2002c-7a9d-4576-9766-4e72bf8f9f83)

因为眼睛看到是一整个画面，有视角，但视角难以分析，不妨假设眼睛只能看到视觉中心（过光轴）的那一个点
太阳经过散射后，并不全部都被散射，一部分保持原有路径继续穿透空气传播，若视线平行太阳方向，则会看到以穿透部分为主的光，是白色；而仰头，则只看到散射光，是蓝色

**Comment by Devil-SX** [comment]
# 不同时刻天空颜色的讨论

激发吸收光谱我不知道会造成怎样的影响，看你贴的wiki似乎会导致颜色的渐变，而也与其余时刻颜色的变化相关。因为blog中的简单假设模型，对任意时刻只要有太阳光都是适用的，傍晚的天空也将是蓝色。也许加上这一项修正，就能扩展到其余天空颜色解释，还是说要修正大气层的厚度？

另外，单纯从直觉出发，如果成分简单只是吸收几道特定频率，因为最后颜色是积分，似乎并不对积分结果产生影响，不知道这里那里要修正

**Comment by Devil-SX** [comment]
> 我之前听说的版本是黑体辐射谱里紫光太少，所以最后人看到的是白光。今天看到你讨论颜色混合，觉得更有道理

准确来说是可见光范围内本身紫色频率范围极窄。

这种情况也有可能，可能由于和波长四次方成反比，最后的红光部分波长压根没有对颜色造成影响，而紫光波长范围极短造成影响也有限，最后只留下波长范围比较长，且波长相对较短的蓝光占据主要影响。

这个验证实验也好做，将红光部分的光强直接修正到0（构造一个类似sigmoid的连续函数让红色那一段接近为0），再看最后产生的颜色。

**Comment by YDX-2147483647** [comment]
> 只是吸收几道特定频率

好像不是这样……

[![Atmospheric_Transmission svg](https://github.com/user-attachments/assets/a5c6066d-0a50-4958-85ff-9698db2228e1)](https://commons.wikimedia.org/wiki/File:Atmospheric_Transmission.svg)

**Comment by YDX-2147483647** [comment]
> 有视角

有道理，我之前有两个地方理解错了。

- 人眼观察到的不是到某点的光的总和，而是到某点且沿某一方向的光的总和。

  人眼这个透镜把来自不同方向的平行光聚焦到了不同地方。

- Rayleigh散射只描述小物体感应后辐射出的场，不包括原本的外场。

  我之前看 $(1 + \cos^2 θ) / 2$ 最小值非负，一直以为已经包括外场了。刚才看了一下 https://engineering.purdue.edu/wcchew/ece604f19/Lecture%20Notes/Lect34.pdf ，发现单个平面波导致的单次散射就是偶极子辐射，确实在极化强度的方向（也就是外场的电场方向）没有辐射，但多种偏振的平面波平均下来，就各个方向都有辐射了：

```math
\int_0^{2\pi} (\sin^2\theta \cos^2\varphi + \cos^2\theta) \frac{\mathrm{d}\varphi}{2\pi} = \frac{1 + \cos^2\theta} {2}.
```

**Comment by YDX-2147483647** [comment]
基本都解决了，那我就先关了。 `\(￣︶￣*\))`
